### ISSUE TITLE
ISSUE?: Want to define location of storage

### ISSUE THREAD

**Issue by olvier** [DeanCording/node-red-contrib-persist#2]
Hi,

I just added your node, but I am not able to define to location of the persistance.json.

Whether `".node-red/persistance.json"` nor `~/.node-red/persistance.json` worked.

What's your idea of using different storage-location?

Kind regards

**Comment by DeanCording** [comment]
It depends a bit on how you are running Node Red as to where the default location is and how you reference other locations.  Typically the Node Red working directory is the install directory which is `.node-red` in the home directory of the user running Node Red, though this can be changed in the settings.js file under userDir.

So, `.node-red/persistance.json` actually translates to something like `/home/userid/.node-red/.node-red/persistance.json` which probably doesn't exist.

`~/.node-red/persistance.json` doesn't work either because `~` is a shell path expansion feature and not available in the underlying C library.

So the options are:

`persistance.json` which will locate it in the Node Red working directory, usually `~/.node-red/persistance.json`

`/home/userid/.node-red/persistance.json` which is the full path and can point to anywhere writable

`../some-other-directory/persistance.json` which is located relative to the Node Red working directory.

**Comment by olvier** [comment]
> Typically the Node Red working directory is the install directory which is `.node-red` in the home directory of the user running Node Red, though this can be changed in the settings.js file under userDir.

Didn't changed location in my `settings.js`. All my node-red files are located in `~/.node-red`.
"Your" `persistance.json`-file is the only one in my `~`.

> So, `.node-red/persistance.json` actually translates to something like `/home/userid/.node-red/.node-red/persistance.json` which probably doesn't exist.

So, from my point of view, my `.node-red/persistance.json` should be stored in `~/.node-red/persistance.json`, because all other files of node-red are stored in `~/.node-red`, too.

> So the options are:
>
>`persistance.json` which will locate it in the Node Red working directory, usually `~/.node-red/persistance.json`

Because this is not happening in my case, i will try the second option.
so, thank you for your hint with the non working `~`, didn't knew that :)

Kind regards



edit:

> So, `.node-red/persistance.json` actually translates to something like `/home/userid/.node-red/.node-red/persistance.json` which probably doesn't exist.

Tested `.node-red/persistance.json` (again) and it works now. As I have seen, I had written in my opening post, that this won't work. No idea where the error was.

**Comment by MDAR** [comment]
I've defined the exact location for the .json file and it seems to be working well.

for example, I created a file here - `/etc/openhab2/nodered-db/persistence.json`

and set the read write flags for all users.
`chmod 0666 *json`
